"""empty message

Revision ID: b8757591cdf9
Revises: 015954272231
Create Date: 2022-02-22 15:29:31.615513

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b8757591cdf9'
down_revision = '015954272231'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('blog', 'author',
               existing_type=sa.INTEGER(),
               nullable='True')
    op.alter_column('comment', 'author',
               existing_type=sa.INTEGER(),
               nullable='True')
    op.alter_column('comment', 'post_id',
               existing_type=sa.INTEGER(),
               nullable='True')
    op.alter_column('comment', 'blog_id',
               existing_type=sa.INTEGER(),
               nullable='True')
    op.add_column('home', sa.Column('headings', sa.String(), nullable=True))
    op.add_column('home', sa.Column('details', sa.Text(), nullable=True))
    op.drop_column('home', 'headings2')
    op.drop_column('home', 'details6')
    op.drop_column('home', 'details1')
    op.drop_column('home', 'details2')
    op.drop_column('home', 'headings6')
    op.drop_column('home', 'headings3')
    op.drop_column('home', 'headings1')
    op.drop_column('home', 'details4')
    op.drop_column('home', 'details5')
    op.drop_column('home', 'headings4')
    op.drop_column('home', 'details3')
    op.drop_column('home', 'headings5')
    op.add_column('home2', sa.Column('headings', sa.String(), nullable=True))
    op.drop_column('home2', 'headings2')
    op.drop_column('home2', 'details6')
    op.drop_column('home2', 'details2')
    op.drop_column('home2', 'headings6')
    op.drop_column('home2', 'headings3')
    op.drop_column('home2', 'details4')
    op.drop_column('home2', 'details5')
    op.drop_column('home2', 'headings4')
    op.drop_column('home2', 'details3')
    op.drop_column('home2', 'headings5')
    op.add_column('home3', sa.Column('headings', sa.String(), nullable=True))
    op.drop_column('home3', 'details6')
    op.drop_column('home3', 'headings6')
    op.drop_column('home3', 'headings3')
    op.drop_column('home3', 'details4')
    op.drop_column('home3', 'details5')
    op.drop_column('home3', 'headings4')
    op.drop_column('home3', 'details3')
    op.drop_column('home3', 'headings5')
    op.alter_column('post', 'author',
               existing_type=sa.INTEGER(),
               nullable='True')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('post', 'author',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.add_column('home3', sa.Column('headings5', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('home3', sa.Column('details3', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('home3', sa.Column('headings4', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('home3', sa.Column('details5', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('home3', sa.Column('details4', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('home3', sa.Column('headings3', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('home3', sa.Column('headings6', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('home3', sa.Column('details6', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('home3', 'headings')
    op.add_column('home2', sa.Column('headings5', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('home2', sa.Column('details3', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('home2', sa.Column('headings4', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('home2', sa.Column('details5', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('home2', sa.Column('details4', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('home2', sa.Column('headings3', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('home2', sa.Column('headings6', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('home2', sa.Column('details2', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('home2', sa.Column('details6', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('home2', sa.Column('headings2', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('home2', 'headings')
    op.add_column('home', sa.Column('headings5', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('home', sa.Column('details3', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('home', sa.Column('headings4', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('home', sa.Column('details5', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('home', sa.Column('details4', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('home', sa.Column('headings1', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('home', sa.Column('headings3', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('home', sa.Column('headings6', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('home', sa.Column('details2', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('home', sa.Column('details1', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('home', sa.Column('details6', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('home', sa.Column('headings2', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('home', 'details')
    op.drop_column('home', 'headings')
    op.alter_column('comment', 'blog_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('comment', 'post_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('comment', 'author',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('blog', 'author',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
