"""empty message

Revision ID: eca199423b79
Revises: a61b019f5ed1
Create Date: 2022-02-12 16:26:18.265979

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eca199423b79'
down_revision = 'a61b019f5ed1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('blog', 'author',
               existing_type=sa.INTEGER(),
               nullable='True')
    op.alter_column('comment', 'author',
               existing_type=sa.INTEGER(),
               nullable='True')
    op.alter_column('comment', 'post_id',
               existing_type=sa.INTEGER(),
               nullable='True')
    op.alter_column('comment', 'blog_id',
               existing_type=sa.INTEGER(),
               nullable='True')
    op.alter_column('post', 'author',
               existing_type=sa.INTEGER(),
               nullable='True')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('post', 'author',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('comment', 'blog_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('comment', 'post_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('comment', 'author',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('blog', 'author',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
